#!/usr/bin/env bash
echo "Content-type: text/plain"
echo ""
echo "rtsp2mjpg by @beardedtek"
echo "See https://github.com/beardedtek-com/rtsp2mjpg for more information"
echo ""
echo "  /mjpg.cgi - converts RTSP/RTMP/MP4 source to MJPG stream"
echo "  /jpg.cgi - takes a snapshot of an RTSP/RTMP stream"
echo "  /layer.cgi - takes a snapshot and saves it to /data/timelapse/ for timelapse videos"
echo ""
echo "## NOT YET IMPLEMENTED FEATURES ##"
echo "##/timelapse.cgi - generates timelapse using jpegs in /data/timelapse/"